# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/arg/Documents/GitHub/FPGA/First_Project/First_Project.srcs/sources_1/ip/big_bram/big_bram.xci
# IP: The module: 'big_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arg/Documents/GitHub/FPGA/First_Project/First_Project.gen/sources_1/ip/big_bram/big_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'big_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/arg/Documents/GitHub/FPGA/First_Project/First_Project.srcs/sources_1/ip/big_bram/big_bram.xci
# IP: The module: 'big_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arg/Documents/GitHub/FPGA/First_Project/First_Project.gen/sources_1/ip/big_bram/big_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'big_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
