# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/arg/Documents/GitHub/FPGA/First_Project/First_Project.srcs/sources_1/ip/blk_mem_gen_16/blk_mem_gen_16.xci
# IP: The module: 'blk_mem_gen_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arg/Documents/GitHub/FPGA/First_Project/First_Project.gen/sources_1/ip/blk_mem_gen_16/blk_mem_gen_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_16'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/arg/Documents/GitHub/FPGA/First_Project/First_Project.srcs/sources_1/ip/blk_mem_gen_16/blk_mem_gen_16.xci
# IP: The module: 'blk_mem_gen_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arg/Documents/GitHub/FPGA/First_Project/First_Project.gen/sources_1/ip/blk_mem_gen_16/blk_mem_gen_16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
