# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Basys3_Master.xdc

# IP: ip/blk_mem_gen_10/blk_mem_gen_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_10 || ORIG_REF_NAME==blk_mem_gen_10} -quiet] -quiet
